version: "3.4"
services:
  backend:
    container_name: backend
    hostname: backend
    image: ksproska/cinema-backend-ticket-collector
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jinstance.cdkuk0q2a24a.us-east-1.rds.amazonaws.com/jinstance
      SPRING_DATASOURCE_USERNAME: jinstance
      SPRING_DATASOURCE_PASSWORD: rootroot
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    network_mode: host
