version: "2.4"
services:
  payment-service:
    container_name: payment-service
    hostname: payment-service
    image: nginx:latest
    networks:
      - priv-network
    ports:
      - "8000:80"
    volumes:
      - ./payment-service:/usr/share/nginx/html

  frontend: # temp frontend to test payment
    image: nginx:latest
    networks:
      - priv-network
    ports:
      - "80:80"
    volumes:
      - ./temp_frontend:/usr/share/nginx/html

networks:
  priv-network:
    driver: bridge
